export const USERS_ADD = 'USERS_ADD';
export const USERS_FETCH = 'USERS_FETCH';
export const USERS_FETCH_ERROR = 'USERS_FETCH_ERROR';

export const USER_TOGGLE_SHOW_VEHICLES = 'USER_TOGGLE_SHOW_VEHICLES';
export const USER_FETCH_VEHICLES = 'USER_FETCH_VEHICLES';
export const USER_ADD_VEHICLES = 'USER_ADD_VEHICLES';